import React, { useState, useEffect } from 'react';
import { Search, Sparkles, Stethoscope, ArrowRight, Loader2 } from 'lucide-react';
import axiosClient from '../api/axiosClient';

export const HeroSearch = ({ onSearchResults, onSelectDisease }) => {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [autocomplete, setAutocomplete] = useState([]);
  const [showDropdown, setShowDropdown] = useState(false);
  const [generationNotice, setGenerationNotice] = useState('');

  // Auto-search dropdown on typing
  useEffect(() => {
    if (!query.trim()) {
      setAutocomplete([]);
      setShowDropdown(false);
      return;
    }

    const timer = setTimeout(async () => {
      try {
        const res = await axiosClient.get(`/api/diseases/search?query=${encodeURIComponent(query)}`);
        if (res.data.success) {
          setAutocomplete(res.data.data);
          setShowDropdown(true);
        }
      } catch (e) {
        console.warn('Autocomplete fetch error');
      }
    }, 200);

    return () => clearTimeout(timer);
  }, [query]);

  const handleExecuteSearch = async (e) => {
    if (e) e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setShowDropdown(false);
    setGenerationNotice(`Generating clinical insights for "${query.trim()}"...`);

    try {
      const res = await axiosClient.get(`/api/diseases/search?query=${encodeURIComponent(query.trim())}`);
      if (res.data.success) {
        onSearchResults(res.data.data, query.trim(), res.data.isAutoGenerated);
        if (res.data.data.length > 0) {
          onSelectDisease(res.data.data[0]);
        }
      }
    } catch (err) {
      console.error('Search execution error:', err);
    } finally {
      setLoading(false);
      setTimeout(() => setGenerationNotice(''), 3000);
    }
  };

  const handleSelectAutocompleteItem = (disease) => {
    onSelectDisease(disease);
    setQuery(disease.name);
    setShowDropdown(false);
  };

  const sampleSearches = ['Viral Fever', 'Tuberculosis', 'Dengue', 'Typhoid', 'Migraine', 'Gastritis', 'Asthma', 'Diabetes'];

  return (
    <div className="relative w-full max-w-4xl mx-auto text-center pt-10 pb-6">
      
      {/* Badge */}
      <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-cyan-950/80 border border-cyan-500/40 text-cyan-400 text-xs font-semibold mb-6 shadow-lg shadow-cyan-950/50">
        <Sparkles className="w-4 h-4 text-cyan-400 animate-spin" />
        <span>Clinical Intelligence & Symptom Diagnostics Engine</span>
      </div>

      {/* Main Heading */}
      <h1 className="text-4xl sm:text-6xl font-black text-white tracking-tight leading-tight">
        Precision Healthcare <br />
        <span className="text-gradient-cyan">Intelligence at Your Fingertips</span>
      </h1>
      
      <p className="mt-4 text-slate-400 text-base sm:text-lg max-w-2xl mx-auto">
        Search any medical condition or symptom term to instantly retrieve clinical dossier presentations, first-aid protocols, and prescription summaries.
      </p>

      {/* Streamlined Search Bar */}
      <div className="relative max-w-3xl mx-auto mt-10">
        <form onSubmit={handleExecuteSearch} className="relative flex items-center">
          
          <div className="absolute left-5 flex items-center pointer-events-none text-slate-500">
            <Stethoscope className="w-5 h-5 text-cyan-400" />
          </div>

          <input
            type="text"
            placeholder="Search condition or symptom (e.g., Tuberculosis, Fever, Migraine, Typhoid)..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onFocus={() => query.trim() && setShowDropdown(true)}
            className="w-full pl-14 pr-36 py-5 rounded-2xl bg-slate-900/90 border-2 border-cyan-500/40 focus:border-cyan-400 text-white placeholder-slate-500 text-base shadow-2xl focus:outline-none focus:ring-4 focus:ring-cyan-500/20 glass-card transition-all"
          />

          {/* Prominent Search Button on Right */}
          <button
            type="submit"
            disabled={loading}
            className="absolute right-2.5 px-6 py-3.5 rounded-xl bg-gradient-to-r from-cyan-500 to-emerald-500 hover:from-cyan-400 hover:to-emerald-400 text-slate-950 font-black text-sm flex items-center gap-2 shadow-lg shadow-cyan-500/25 transition-all cursor-pointer"
          >
            {loading ? (
              <div className="w-5 h-5 border-2 border-slate-950 border-t-transparent rounded-full animate-spin" />
            ) : (
              <>
                <Search className="w-4 h-4 stroke-[3]" />
                <span>SEARCH</span>
              </>
            )}
          </button>
        </form>

        {/* Search Feedback Banner */}
        {generationNotice && (
          <div className="mt-3 p-3 rounded-xl bg-cyan-950/80 border border-cyan-500/50 text-cyan-300 text-xs font-semibold flex items-center justify-center gap-2 animate-pulse glow-cyan">
            <Loader2 className="w-4 h-4 text-cyan-400 animate-spin" />
            <span>✨ {generationNotice}</span>
          </div>
        )}

        {/* Quick Suggestion Pills */}
        <div className="flex flex-wrap items-center justify-center gap-2 mt-4 text-xs text-slate-400">
          <span className="font-semibold text-slate-500">Popular Queries:</span>
          {sampleSearches.map((term) => (
            <button
              key={term}
              onClick={() => {
                setQuery(term);
                setLoading(true);
                setGenerationNotice(`Generating clinical insights for "${term}"...`);
                axiosClient.get(`/api/diseases/search?query=${encodeURIComponent(term)}`)
                  .then(res => {
                    if (res.data.success) {
                      onSearchResults(res.data.data, term, res.data.isAutoGenerated);
                      if (res.data.data.length > 0) onSelectDisease(res.data.data[0]);
                    }
                  })
                  .finally(() => {
                    setLoading(false);
                    setTimeout(() => setGenerationNotice(''), 3000);
                  });
              }}
              className="px-3 py-1 rounded-lg bg-slate-900/80 hover:bg-cyan-950 text-slate-300 hover:text-cyan-300 border border-white/10 hover:border-cyan-500/40 transition-all cursor-pointer"
            >
              {term}
            </button>
          ))}
        </div>

        {/* Autocomplete Dropdown */}
        {showDropdown && autocomplete.length > 0 && (
          <div className="absolute top-full left-0 right-0 mt-3 z-30 bg-slate-900 border border-cyan-500/40 rounded-2xl shadow-2xl overflow-hidden glass-card max-h-80 overflow-y-auto text-left">
            <div className="p-3 border-b border-white/10 text-[11px] font-bold uppercase tracking-wider text-cyan-400 px-4 bg-slate-950">
              Matched Clinical Records ({autocomplete.length})
            </div>
            {autocomplete.map((disease) => (
              <div
                key={disease._id || disease.name}
                onClick={() => handleSelectAutocompleteItem(disease)}
                className="p-4 hover:bg-cyan-950/50 border-b border-white/5 last:border-0 cursor-pointer flex items-center justify-between group transition-colors"
              >
                <div>
                  <h4 className="text-sm font-bold text-white group-hover:text-cyan-400 transition-colors">
                    {disease.name}
                  </h4>
                  <p className="text-xs text-slate-400 truncate max-w-md mt-0.5">
                    Symptoms: {disease.symptoms.join(', ')}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full ${
                    disease.severity === 'Critical' ? 'bg-rose-950 text-rose-400 border border-rose-800' :
                    disease.severity === 'Moderate' ? 'bg-amber-950 text-amber-400 border border-amber-800' :
                    'bg-emerald-950 text-emerald-400 border border-emerald-800'
                  }`}>
                    {disease.severity}
                  </span>
                  <ArrowRight className="w-4 h-4 text-slate-500 group-hover:text-cyan-400 group-hover:translate-x-1 transition-all" />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
};
