import React, { useState, useEffect } from 'react';
import { AuthProvider } from './context/AuthContext';
import { Navbar } from './components/Navbar';
import { HeroSearch } from './components/HeroSearch';
import { ConditionDossier } from './components/ConditionDossier';
import { PrescriptionScanner } from './components/PrescriptionScanner';
import { BookmarksDrawer } from './components/BookmarksDrawer';
import { AuthModal } from './components/AuthModal';
import { DisclaimerFooter } from './components/DisclaimerFooter';
import { Search, ChevronRight, Sparkles } from 'lucide-react';
import axiosClient from './api/axiosClient';

const MainApp = () => {
  const [selectedDisease, setSelectedDisease] = useState(null);
  const [searchResults, setSearchResults] = useState([]);
  const [activeQuery, setActiveQuery] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  
  // Modals state
  const [isBookmarksOpen, setIsBookmarksOpen] = useState(false);
  const [isAuthOpen, setIsAuthOpen] = useState(false);

  // Initial load: fetch default conditions
  useEffect(() => {
    const loadInitialData = async () => {
      try {
        const res = await axiosClient.get('/api/diseases/search?query=');
        if (res.data.success && res.data.data.length > 0) {
          setSearchResults(res.data.data);
          setSelectedDisease(res.data.data[0]);
        }
      } catch (e) {
        console.warn('Initial condition load error');
      }
    };
    loadInitialData();
  }, []);

  return (
    <div className="min-h-screen bg-[#0B0F17] text-slate-100 flex flex-col font-sans selection:bg-cyan-500 selection:text-slate-950">
      
      {/* Navigation Header */}
      <Navbar
        onOpenBookmarks={() => setIsBookmarksOpen(true)}
        onOpenAuth={() => setIsAuthOpen(true)}
      />

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        
        {/* Streamlined Omni-Search Hub */}
        <HeroSearch
          onSelectDisease={(disease) => {
            setSelectedDisease(disease);
          }}
          onSearchResults={(results, queryStr, autoGenFlag) => {
            setSearchResults(results);
            setActiveQuery(queryStr);
            setIsAutoGenerated(!!autoGenFlag);
            if (results && results.length > 0) {
              setSelectedDisease(results[0]);
            }
          }}
        />

        {/* Dynamic Auto-Generation Banner */}
        {isAutoGenerated && selectedDisease && (
          <div className="p-4 rounded-2xl bg-cyan-950/60 border border-cyan-500/50 text-cyan-300 text-xs font-semibold flex items-center justify-between max-w-5xl mx-auto shadow-lg shadow-cyan-950/40 glow-cyan">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-cyan-400 animate-spin" />
              <span>
                <strong>Clinical Intelligence Engine:</strong> Generated structured dynamic dossier for <span className="text-white font-bold">"{selectedDisease.name}"</span> and persisted record to database.
              </span>
            </div>
            <span className="text-[10px] uppercase font-black px-2 py-0.5 rounded-full bg-cyan-900 text-cyan-200 border border-cyan-700">
              AI Auto-Dossier
            </span>
          </div>
        )}

        {/* Selected Disease Dossier Display */}
        {selectedDisease && (
          <div id="dossier-view" className="scroll-mt-24">
            <ConditionDossier
              disease={selectedDisease}
              onClose={() => setSelectedDisease(null)}
            />
          </div>
        )}

        {/* Search Results Summary Cards (if multiple results found) */}
        {searchResults.length > 1 && (
          <div className="p-6 rounded-3xl bg-slate-900 border border-white/10 glass-card space-y-4 text-left">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <span className="text-sm font-bold text-white flex items-center gap-2">
                <Search className="w-4 h-4 text-cyan-400" />
                <span>Search Results for "{activeQuery || 'Conditions'}" ({searchResults.length} Records)</span>
              </span>
              <span className="text-xs text-slate-400">Click any card to view dossier</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {searchResults.map((item) => (
                <div
                  key={item._id || item.name}
                  onClick={() => {
                    setSelectedDisease(item);
                    const el = document.getElementById('dossier-view');
                    if (el) el.scrollIntoView({ behavior: 'smooth' });
                  }}
                  className={`p-4 rounded-2xl border cursor-pointer transition-all flex items-center justify-between group ${
                    selectedDisease?.name === item.name
                      ? 'bg-cyan-950/60 border-cyan-400 glow-cyan'
                      : 'bg-slate-950/80 border-white/10 hover:border-cyan-500/40'
                  }`}
                >
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <h4 className="text-sm font-bold text-white group-hover:text-cyan-400 transition-colors">
                        {item.name}
                      </h4>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        item.severity === 'Critical' ? 'bg-rose-950 text-rose-400 border border-rose-800' :
                        item.severity === 'Moderate' ? 'bg-amber-950 text-amber-400 border border-amber-800' :
                        'bg-emerald-950 text-emerald-400 border border-emerald-800'
                      }`}>
                        {item.severity}
                      </span>
                    </div>
                    <p className="text-xs text-slate-400 truncate max-w-[200px]">
                      {item.symptoms.join(', ')}
                    </p>
                  </div>

                  <ChevronRight className="w-5 h-5 text-slate-500 group-hover:text-cyan-400 group-hover:translate-x-1 transition-all" />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Prescription OCR Scanner Section */}
        <section className="pt-8 border-t border-white/10">
          <PrescriptionScanner
            onSelectDisease={(disease) => {
              setSelectedDisease(disease);
              const el = document.getElementById('dossier-view');
              if (el) el.scrollIntoView({ behavior: 'smooth' });
            }}
          />
        </section>

      </main>

      {/* Drawers & Modals */}
      <BookmarksDrawer
        isOpen={isBookmarksOpen}
        onClose={() => setIsBookmarksOpen(false)}
        onSelectDisease={(disease) => {
          setSelectedDisease(disease);
          const el = document.getElementById('dossier-view');
          if (el) el.scrollIntoView({ behavior: 'smooth' });
        }}
      />

      <AuthModal
        isOpen={isAuthOpen}
        onClose={() => setIsAuthOpen(false)}
      />

      {/* Global Regulatory Footer */}
      <DisclaimerFooter />

    </div>
  );
};

export default function App() {
  return (
    <AuthProvider>
      <MainApp />
    </AuthProvider>
  );
}
